// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jltbjzubshtuykidfwma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsdGJqenVic2h0dXlraWRmd21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODIxNjgsImV4cCI6MjA1Nzc1ODE2OH0.Y9Fr0YDEVtRKQ9q9xo2AHyBizYYNV-SFhV1xhU_CKrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);